WHITESPACE = { (" " | "\t")}
MARK = { !ASCII_ALPHANUMERIC ~ !NEWLINE ~ ASCII }
word ={ ASCII_ALPHANUMERIC+ }
words = { word ~ (WHITESPACE+ ~ word)* }
headings1 = {("# " | "## " | "### " | "#### " | "##### " | "###### ") ~ (words | MARK)+ ~ NEWLINE}
headings2 = {NEWLINE* ~ (words | MARK)+ ~ NEWLINE ~ ("=="+ | "--"+) ~ NEWLINE}
headings = { (headings1 | headings2)}
italic1 = {"*" ~ (words | (!"*" ~ MARK))+ ~ "*"}
italic2 = {"_" ~ (words | (!"_" ~ MARK))+ ~ "_"}
italic = { (italic1 | italic2) }
paragraph = {NEWLINE* ~ (words | MARK | (NEWLINE ~ !NEWLINE))+ ~ NEWLINE ~ NEWLINE}

